version: "3.7"
services:
  jormungandr-alpine:
    build: .
    container_name: coregdx/pool-cert
    image: coregdx/pool-cert:latest
    env_file:
      - ./pool.env
    command: 
      - /bin/sh
      - -c
      - |
        echo "Hello World"
