version: "3.7"
services:
  coregdx-jormungandr-poolkey:
    build: .
    container_name: coregdx-jormungandr-poolkey
    image: coregdx/pool-key:latest
    command: 
      - /bin/sh
      - -c
      - |
        rm -rf poolkey
        mkdir poolkey
        jcli key generate --type=Ed25519 > poolkey/owner_key.prv
        cat poolkey/owner_key.prv | jcli key to-public > poolkey/owner_key.pub
        tail -f /dev/null
