version: "3.7"
services:
  coregdx-jormungandr-poolcert:
    build: .
    container_name: coregdx-jormungandr-poolcert
    image: coregdx/pool-cert:latest
    env_file:
      - ./pool.env
    command: 
      - /bin/sh
      - -c
      - |
        rm -rf poolgen
        mkdir poolgen
        jcli key generate --type=Curve25519_2HashDH > poolgen/stake_pool_vrf.prv
        cat poolgen/stake_pool_vrf.prv | jcli key to-public > poolgen/stake_pool_vrf.pub
        jcli key generate --type=SumEd25519_12 > poolgen/stake_pool_kes.prv
        cat poolgen/stake_pool_kes.prv | jcli key to-public > poolgen/stake_pool_kes.pub
        jcli certificate new stake-pool-registration --kes-key $$(cat poolgen/stake_pool_kes.pub) --vrf-key $$(cat poolgen/stake_pool_vrf.pub) --start-validity 0 --management-threshold 1 --tax-fixed $$POOL_TAX_FIXED --tax-limit $$POOL_TAX_LIMIT --tax-ratio $$POOL_TAX_RATIO --owner $$POOL_OWNER_PUBLIC_KEY > poolgen/stake_pool.cert
        cat poolgen/stake_pool.cert | jcli certificate get-stake-pool-id | tee stake_pool.id > poolgen/node_id.txt
        tail -f /dev/null
