# Use the pre-compiled version of jormungandr for Alpine
# Dockerfile can be found in https://github.com/CoreGDX/cardano-alpine-base
FROM coregdx/jormungandr:release-0.8.6-rc0
LABEL MAINTAINER CoreGDX-(DavidArayan)
WORKDIR /usr/cardano/jormungandr/bin